### ISSUE TITLE
panic: semaphore: released more than held

### ISSUE THREAD

**Issue by zhangguanzhang** [containers/image#1022]
```
goroutine 793495 [running]:
golang.org/x/sync/semaphore.(*Weighted).Release(0xc00097ee60, 0x1)
	/home/travis/gopath/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/semaphore/semaphore.go:98 +0x1f5
github.com/containers/image/copy.(*imageCopier).copyLayers.func1(0xe, 0xc0008f0fa0, 0x47, 0x655be, 0x0, 0x0, 0x0, 0x0, 0xc00093ac80, 0x31, ...)
	/home/travis/gopath/pkg/mod/github.com/containers/image@v3.0.2+incompatible/copy/copy.go:489 +0x241
created by github.com/containers/image/copy.(*imageCopier).copyLayers.func2
	/home/travis/gopath/pkg/mod/github.com/containers/image@v3.0.2+incompatible/copy/copy.go:497 +0x1f6
```
go.mod
```
github.com/containers/image v3.0.2+incompatible
```
go.sum
```
github.com/containers/image v3.0.2+incompatible h1:B1lqAE8MUPCrsBLE86J0gnXleeRq8zJnQryhiiGQNyE=
github.com/containers/image v3.0.2+incompatible/go.mod h1:8Vtij257IWSanUQKe1tAeNOm2sRVkSqQTVQ1IlwI3+M=
```

**Comment by mtrmac** [comment]
Thanks for your report. Please update to a recent version; can you reproduce it then?

**Comment by zhangguanzhang** [comment]
I will try later
